version: '2'
services:
   spark-master:
      image: quay.io/geodocker/spark:8fd1a50
      command: master
      ports:
         - 4040:4040
         - 8080:8080
   spark-worker:
      image: quay.io/geodocker/spark:8fd1a50
      command: worker
      environment:
         SPARK_MASTER: spark-master
      depends_on:
         - spark-master
   jupyter:
      image: quay.io/geodocker/geotrellis-jupyter:9b577f1
      command: /scripts/geodocker.sh
      ports:
         - 8000:8000
      depends_on:
         - spark-master
